Fix variables being used before being assigned
TSError:
src/baseConn.ts:533:9 - error TS2454: Variable 'inTypeId' is used before being assigned.
src/baseConn.ts:533:29 - error TS2454: Variable 'outTypeId' is used before being assigned.
src/baseConn.ts:619:9 - error TS2454: Variable 'cardinality' is used before being assigned.